# Generated by Django 5.0.4 on 2024-05-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='hospital',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
