# Generated by Django 5.0.4 on 2024-05-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='donor_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='hospital',
            field=models.CharField(default='', max_length=100),
        ),
    ]
