# Generated by Django 5.0.4 on 2024-05-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hospital_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='hospital/images'),
        ),
    ]
